// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpcproto/manager_update.proto

// Copyright (c) 2018 Donovan Solms / MiningHQ. Licensed under the MIT license.
// See LICENSE in the root of this repository for details.

package rpcproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ManagerUpdate holds all the information for updating the manager interface
type ManagerUpdate struct {
	// State of the miner
	State MinerState `protobuf:"varint,1,opt,name=State,proto3,enum=rpcproto.MinerState" json:"State,omitempty"`
	// Stats if we're mining
	Stats *MinerStats `protobuf:"bytes,2,opt,name=Stats,proto3" json:"Stats,omitempty"`
	// Logs is the combined logs from all miners
	HTMLLogs             string   `protobuf:"bytes,3,opt,name=HTMLLogs,proto3" json:"HTMLLogs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ManagerUpdate) Reset()         { *m = ManagerUpdate{} }
func (m *ManagerUpdate) String() string { return proto.CompactTextString(m) }
func (*ManagerUpdate) ProtoMessage()    {}
func (*ManagerUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd1016a7e06f7e2d, []int{0}
}

func (m *ManagerUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManagerUpdate.Unmarshal(m, b)
}
func (m *ManagerUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManagerUpdate.Marshal(b, m, deterministic)
}
func (m *ManagerUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManagerUpdate.Merge(m, src)
}
func (m *ManagerUpdate) XXX_Size() int {
	return xxx_messageInfo_ManagerUpdate.Size(m)
}
func (m *ManagerUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ManagerUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ManagerUpdate proto.InternalMessageInfo

func (m *ManagerUpdate) GetState() MinerState {
	if m != nil {
		return m.State
	}
	return MinerState_UnknownState
}

func (m *ManagerUpdate) GetStats() *MinerStats {
	if m != nil {
		return m.Stats
	}
	return nil
}

func (m *ManagerUpdate) GetHTMLLogs() string {
	if m != nil {
		return m.HTMLLogs
	}
	return ""
}

func init() {
	proto.RegisterType((*ManagerUpdate)(nil), "rpcproto.ManagerUpdate")
}

func init() { proto.RegisterFile("rpcproto/manager_update.proto", fileDescriptor_cd1016a7e06f7e2d) }

var fileDescriptor_cd1016a7e06f7e2d = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2d, 0x2a, 0x48, 0x2e,
	0x28, 0xca, 0x2f, 0xc9, 0xd7, 0xcf, 0x4d, 0xcc, 0x4b, 0x4c, 0x4f, 0x2d, 0x8a, 0x2f, 0x2d, 0x48,
	0x49, 0x2c, 0x49, 0xd5, 0x03, 0x0b, 0x0a, 0x71, 0xc0, 0xa4, 0xa5, 0x44, 0xe0, 0x0a, 0x8b, 0x4b,
	0xe0, 0xf2, 0x68, 0xa2, 0xc5, 0x10, 0x51, 0xa5, 0x66, 0x46, 0x2e, 0x5e, 0x5f, 0x88, 0x71, 0xa1,
	0x60, 0xd3, 0x84, 0xb4, 0xb8, 0x58, 0x83, 0x41, 0xda, 0x24, 0x18, 0x15, 0x18, 0x35, 0xf8, 0x8c,
	0x44, 0xf4, 0x60, 0xfa, 0xf4, 0x7c, 0x33, 0xf3, 0x52, 0x8b, 0xc0, 0x72, 0x41, 0x10, 0x25, 0x30,
	0xb5, 0xc5, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xdc, 0x58, 0xd5, 0x16, 0x43, 0xd4, 0x16, 0x0b, 0x49,
	0x71, 0x71, 0x78, 0x84, 0xf8, 0xfa, 0xf8, 0xe4, 0xa7, 0x17, 0x4b, 0x30, 0x2b, 0x30, 0x6a, 0x70,
	0x06, 0xc1, 0xf9, 0x49, 0x6c, 0x60, 0x4d, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x30, 0xa5,
	0xaf, 0x62, 0xe3, 0x00, 0x00, 0x00,
}
